rules:
  unpinned-uses:
    ignore:
      - dependabot-changie.yaml:32
      - triage.yaml:18
  bot-conditions:
    ignore:
      - dependabot-changie.yaml:15
  cache-poisoning:
    ignore:
      - pull-request.yaml:17
      - release.yaml:15
