version: '3'

tasks:
  build:
    env:
      GORELEASER_CURRENT_TAG: "v0.0.0"
    cmd: goreleaser build --snapshot --clean --single-target --output terraform-provider-amplience

  format:
    cmds:
      - go fmt ./...

  test:
    cmds:
      - go test -v ./...

  docs:
    cmds:
      - go generate ./...

  coverage-html:
    cmds:
      - go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... ./...
      - go tool cover -html=coverage.txt

  coverage:
    cmds:
      - go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... ./...
      - go tool cover -func=coverage.txt

  testacc:
    cmds:
      - TF_ACC=1 go test -v ./...

  testacct:
    cmds:
      - TF_ACC=1 go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... -v ./...
