name: Generate release pull request

on:
  push:
    branches: [ "main" ]

jobs:
  generate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0

      - name: Prepare release
        uses: labd/changie-release-action@c3368fda69f814cd8b78d36834fb154254ea8c23 # v0.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-workflow: release.yaml
