name: Run Tests

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        go-version: ["1.19.x"]

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go get ./amplience

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --issues-exit-code=0

      - name: Run tests
        run: go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
        env:
          # we need an AMPLIENCE_HUB_ID dedicated to testing
          # TF_ACC: 1
          AMPLIENCE_CLIENT_ID: ${{ secrets.AMPLIENCE_CLIENT_ID }}
          AMPLIENCE_CLIENT_SECRET: ${{ secrets.AMPLIENCE_CLIENT_SECRET }}
          AMPLIENCE_HUB_ID: ${{ secrets.AMPLIENCE_HUB_ID }}

      - name: Upload to codecov
        uses: codecov/codecov-action@v1.0.6
