name: Run Tests

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - name: Install dependencies
        run: go get ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          args: --issues-exit-code=0

      - name: Run tests
        run: go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
        env:
          # we need an AMPLIENCE_HUB_ID dedicated to testing
          # TF_ACC: 1
          AMPLIENCE_CLIENT_ID: ${{ secrets.AMPLIENCE_CLIENT_ID }}
          AMPLIENCE_CLIENT_SECRET: ${{ secrets.AMPLIENCE_CLIENT_SECRET }}
          AMPLIENCE_HUB_ID: ${{ secrets.AMPLIENCE_HUB_ID }}

      - name: Upload to codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true

  changie:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    permissions:
      contents: write
      pull-requests: write
      actions: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare release
        uses: labd/changie-release-action@v0.3.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-workflow: 'release.yaml'
